import {auth,db} from './firebase.js';
import {onAuthStateChanged,signInWithEmailAndPassword,signOut} from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js';
import {ref,get,onValue,push,set,update,remove} from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-database.js';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let products={},cats={},orders={},posts={},settings={},section='dashboard';const statusOptions=['nouvelle','confirmée','préparation','expédiée','livrée','annulée'];
const stat=()=>Object.keys(orders).length;
$('#adminLogin').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);try{await signInWithEmailAndPassword(auth,f.get('email'),f.get('password'))}catch(err){$('#loginError').textContent=err.message}};
onAuthStateChanged(auth,async user=>{if(!user||user.isAnonymous){if($('#layout'))location.reload();return}try{const s=await get(ref(db,'admins/'+user.uid));if(s.val()!==true)throw new Error('Ce compte n’a pas le rôle administrateur. Consultez le README pour ajouter son UID dans la console Firebase.');start()}catch(err){await signOut(auth);$('#loginError').textContent=err.message}});
function start(){$('#adminApp').innerHTML='<div class="admin-layout" id="layout"><aside class="sidebar"><a class="brand" href="./index.html">sporti<span>fano.</span></a>'+[['dashboard','Vue générale'],['products','Produits'],['categories','Catégories'],['orders','Commandes'],['posts','Blog'],['settings','Couverture & annonces']].map(([k,v])=>'<button class="sidebtn" data-section="'+k+'">'+v+'</button>').join('')+'<button class="sidebtn" id="logout">Déconnexion</button></aside><main class="admin-content" id="workspace"></main></div><div id="dialog"></div>';document.querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>{section=b.dataset.section;render()});$('#logout').onclick=()=>signOut(auth);onValue(ref(db,'products'),s=>{products=s.val()||{};render()});onValue(ref(db,'categories'),s=>{cats=s.val()||{};render()});onValue(ref(db,'orders'),s=>{orders=s.val()||{};render()});onValue(ref(db,'posts'),s=>{posts=s.val()||{};render()});onValue(ref(db,'settings'),s=>{settings=s.val()||{};render()});render()}
function dialog(html){$('#dialog').innerHTML='<div class="modal-bg" id="bg"><div class="modal">'+html+'</div></div>';$('#bg').onclick=e=>{if(e.target.id==='bg')close()}}
function close(){$('#dialog').innerHTML=''}
function formFields(items,obj={}){return items.map(([key,label,type])=>'<label>'+label+'</label>'+(type==='textarea'?'<textarea name="'+key+'">'+esc(obj[key]||'')+'</textarea>':type==='checkbox'?'<select name="'+key+'"><option value="true" '+(obj[key]!==false?'selected':'')+'>Visible</option><option value="false" '+(obj[key]===false?'selected':'')+'>Masqué</option></select>':'<input '+(type==='number'?'min="0" step="0.01"':'')+' type="'+(type||'text')+'" name="'+key+'" value="'+esc(obj[key]??'')+'">')).join('')}
function render(){if(!$('#workspace'))return;document.querySelectorAll('[data-section]').forEach(b=>b.classList.toggle('active',b.dataset.section===section));const titles={dashboard:'Vue générale',products:'Gestion des produits',categories:'Catégories',orders:'Commandes clients',posts:'Blog & actualités',settings:'Personnalisation'};let html='<h1 class="page-title">'+titles[section]+'</h1>';
if(section==='dashboard'){html+='<div class="stats"><div class="stat">Produits<b>'+Object.keys(products).length+'</b></div><div class="stat">Commandes<b>'+stat()+'</b></div><div class="stat">Articles<b>'+Object.keys(posts).length+'</b></div></div><div class="panel" style="margin-top:20px"><h3>Bienvenue</h3><p>Depuis ce tableau de bord, publiez vos produits, catégories et actualités. Chaque modification est enregistrée dans Firebase Realtime Database.</p><p class="note">Important : le total financier des commandes doit être recalculé par l'Admin à partir des prix actuels. Aucun paiement en ligne n'est intégré.</p></div>'}
if(section==='products'){html+='<button id="newProduct" class="btn">+ Ajouter un produit</button><div class="panel table-wrap" style="margin-top:18px"><table><thead><tr><th>Produit</th><th>Prix</th><th>Catégorie</th><th>Action</th></tr></thead><tbody>'+Object.entries(products).map(([id,p])=>'<tr><td><img src="'+esc((p.images||[])[0]||'')+'" width="45" height="45" style="object-fit:cover;vertical-align:middle;border-radius:8px" alt=""> '+esc(p.name)+'</td><td>'+Number(p.price||0).toFixed(2)+' DT</td><td>'+esc(cats[p.category]?.name||'—')+'</td><td><button class="btn secondary" data-editprod="'+esc(id)+'">Modifier</button></td></tr>').join('')+'</tbody></table></div>'}
if(section==='categories'){html+='<button id="newCategory" class="btn">+ Nouvelle catégorie</button><div class="panel" style="margin-top:18px">'+Object.entries(cats).map(([id,c])=>'<div class="row between" style="padding:12px;border-bottom:1px solid #e9eeea"><b>'+esc(c.name)+'</b><button class="btn secondary" data-editcat="'+esc(id)+'">Modifier</button></div>').join('')+'</div>'}
if(section==='orders'){html+='<div class="panel table-wrap"><table><thead><tr><th>Référence</th><th>Client</th><th>Articles</th><th>Statut</th></tr></thead><tbody>'+Object.entries(orders).reverse().map(([id,o])=>'<tr><td><button class="btn secondary" data-order="'+esc(id)+'">'+esc(id.slice(-10))+'</button></td><td>'+esc(o.customer?.name||'—')+'<br>'+esc(o.customer?.phone||'')+'</td><td>'+Object.values(o.items||{}).length+'</td><td><span class="badge">'+esc(o.status)+'</span></td></tr>').join('')+'</tbody></table></div>'}
if(section==='posts'){html+='<button class="btn" id="newPost">+ Nouvel article</button><div class="panel" style="margin-top:18px">'+Object.entries(posts).map(([id,p])=>'<div class="row between" style="padding:11px;border-bottom:1px solid #eee"><b>'+esc(p.title)+'</b><button class="btn secondary" data-editpost="'+esc(id)+'">Modifier</button></div>').join('')+'</div>'}
if(section==='settings'){html+='<form id="settingsForm" class="panel">'+formFields([['title','Titre couverture'],['subtitle','Sous-titre','textarea'],['heroImage','URL image couverture','url'],['announcement','Bandeau annonces']],settings)+'<br><br><button class="btn">Enregistrer</button><p class="muted tiny">Images : utilisez des liens directs HTTPS (JPG, PNG, WebP). L’upload Firebase Storage n’est pas utilisé sur Spark.</p><p class="error" id="formError"></p></form>'}
$('#workspace').innerHTML=html;bind()}
function bind(){if($('#newProduct'))$('#newProduct').onclick=()=>productForm();document.querySelectorAll('[data-editprod]').forEach(b=>b.onclick=()=>productForm(b.dataset.editprod));if($('#newCategory'))$('#newCategory').onclick=()=>categoryForm();document.querySelectorAll('[data-editcat]').forEach(b=>b.onclick=()=>categoryForm(b.dataset.editcat));if($('#newPost'))$('#newPost').onclick=()=>postForm();document.querySelectorAll('[data-editpost]').forEach(b=>b.onclick=()=>postForm(b.dataset.editpost));document.querySelectorAll('[data-order]').forEach(b=>b.onclick=()=>orderForm(b.dataset.order));if($('#settingsForm'))$('#settingsForm').onsubmit=async e=>{e.preventDefault();try{await set(ref(db,'settings'),Object.fromEntries(new FormData(e.target)));alert('Modifications publiées')}catch(err){$('#formError').textContent=err.message}}}
function attachForm(handler){$('#closeDialog').onclick=close;$('#editForm').onsubmit=async e=>{e.preventDefault();const btn=e.target.querySelector('[type=submit]');btn.disabled=true;try{await handler(Object.fromEntries(new FormData(e.target)));close();render()}catch(err){$('#formError').textContent=err.message;btn.disabled=false}};if($('#deleteBtn'))$('#deleteBtn').onclick=async()=>{if(confirm('Confirmer la suppression ?')){try{await remove(ref(db,$('#deleteBtn').dataset.path));close()}catch(err){$('#formError').textContent=err.message}}}}
function productForm(id){const p=products[id]||{};dialog('<div class="row between"><h2>'+(id?'Modifier':'Ajouter')+' produit</h2><button class="btn secondary" id="closeDialog">✕</button></div><form id="editForm">'+formFields([['name','Nom du produit'],['price','Prix DT','number'],['oldPrice','Ancien prix DT (facultatif)','number'],['description','Description','textarea'],['stock','Stock indicatif','number'],['colors','Couleurs séparées par virgule'],['sizes','Tailles séparées par virgule'],['delivery','Informations de livraison'],['active','Visibilité','checkbox']],p)+'<label>Catégorie</label><select name="category"><option value="">Aucune</option>'+Object.entries(cats).map(([k,c])=>'<option value="'+esc(k)+'" '+(p.category===k?'selected':'')+'>'+esc(c.name)+'</option>').join('')+'</select><label>Liens photos (une URL directe par ligne)</label><textarea name="images">'+esc((p.images||[]).join('\n'))+'</textarea><p class="muted tiny">Utilisez des URL https://.../image.jpg ou des images hébergées dans votre dépôt GitHub. Pas d’upload natif sur Spark.</p><br><button class="btn" type="submit">Enregistrer</button> '+(id?'<button class="btn danger" type="button" id="deleteBtn" data-path="products/'+esc(id)+'">Supprimer</button>':'')+'<p id="formError" class="error"></p></form>');attachForm(async v=>{if(!v.name.trim())throw Error('Nom obligatoire');if(!Number.isFinite(Number(v.price))||Number(v.price)<0)throw Error('Prix invalide');const images=v.images.split('\n').map(s=>s.trim()).filter(Boolean);if(images.some(s=>!/^https:\/\//i.test(s)&&!/^\.\/assets\//.test(s)))throw Error('Utilisez des URLs HTTPS ou ./assets/...');const obj={...v,images,price:Number(v.price),oldPrice:Number(v.oldPrice||0),stock:Number(v.stock||0),active:v.active==='true',updatedAt:Date.now()};await set(ref(db,'products/'+(id||push(ref(db,'products')).key)),obj)})}
function categoryForm(id){const v=cats[id]||{};dialog('<div class="row between"><h2>Catégorie</h2><button id="closeDialog" class="btn secondary">✕</button></div><form id="editForm">'+formFields([['name','Nom de catégorie']],v)+'<br><br><button class="btn">Enregistrer</button> '+(id?'<button type="button" class="btn danger" id="deleteBtn" data-path="categories/'+esc(id)+'">Supprimer</button>':'')+'<p id="formError" class="error"></p></form>');attachForm(async v=>{if(!v.name.trim())throw Error('Nom obligatoire');await set(ref(db,'categories/'+(id||push(ref(db,'categories')).key)),v)})}
function postForm(id){const v=posts[id]||{};dialog('<div class="row between"><h2>Article</h2><button id="closeDialog" class="btn secondary">✕</button></div><form id="editForm">'+formFields([['title','Titre'],['text','Contenu','textarea'],['image','URL image','url']],v)+'<br><br><button class="btn">Publier</button> '+(id?'<button type="button" class="btn danger" id="deleteBtn" data-path="posts/'+esc(id)+'">Supprimer</button>':'')+'<p id="formError" class="error"></p></form>');attachForm(async v=>{if(!v.title.trim())throw Error('Titre obligatoire');await set(ref(db,'posts/'+(id||push(ref(db,'posts')).key)),{...v,updatedAt:Date.now()})})}
function orderForm(id){const o=orders[id];if(!o)return;dialog('<div class="row between"><h2>Commande</h2><button id="closeDialog" class="btn secondary">✕</button></div><p><b>Référence :</b> '+esc(id)+'</p><p><b>Client :</b> '+esc(o.customer?.name)+' — '+esc(o.customer?.phone)+'</p><p><b>Adresse :</b> '+esc(o.customer?.region)+' / '+esc(o.customer?.address)+'</p><p><b>Note :</b> '+esc(o.customer?.note||'—')+'</p><hr class="divider"><h3>Articles</h3>'+Object.values(o.items||{}).map(x=>'<p>'+esc(products[x.productId]?.name||x.productId)+' × '+Number(x.qty||1)+' · '+esc(x.color||'')+' · '+esc(x.size||'')+'</p>').join('')+'<p class="note">Vérifiez le prix total et la disponibilité avant de confirmer. Le panier client ne constitue pas une preuve du montant.</p><form id="editForm"><label>Statut</label><select name="status">'+statusOptions.map(s=>'<option '+(o.status===s?'selected':'')+'>'+s+'</option>').join('')+'</select><br><br><button class="btn">Mettre à jour</button><p id="formError" class="error"></p></form>');attachForm(async v=>await update(ref(db,'orders/'+id),{status:v.status}))}
